# Generated by Django 6.1 on 2026-09-09 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product name e.g. Herbal Hair Oil', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL friendly identifier', max_length=220, unique=True)),
                ('description', models.TextField(help_text='Detailed product description')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in INR (₹)', max_digits=10)),
                ('image', models.ImageField(blank=True, help_text='Product showcase image', null=True, upload_to='products/')),
                ('category', models.CharField(choices=[('Hair Care', 'Hair Care'), ('Skin Care', 'Skin Care'), ('Body Care', 'Body Care'), ('Herbal Care', 'Herbal Care')], default='Hair Care', max_length=100)),
                ('is_available', models.BooleanField(default=True, help_text='Designate if product is currently available for ordering')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Customer Name')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('message', models.TextField(verbose_name='Enquiry Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted On')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='products.product', verbose_name='Interested Product')),
            ],
            options={
                'verbose_name': 'Customer Enquiry',
                'verbose_name_plural': 'Customer Enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
